=== HamkitSi/HamkitSi.github.io/portfolio-hasina-rakotoarison/tp1/arbres.dtd
<!ELEMENT foret (#PCDATA|arbre)*>
<!ELEMENT arbre (tronc)>
<!ELEMENT tronc (branche*)>
<!ELEMENT branche (branche|feuille)*>
<!ELEMENT feuille EMPTY>

=== HamkitSi/HamkitSi.github.io/portfolio-hasina-rakotoarison/tp1/bon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foret SYSTEM "arbres.dtd">
<foret>
  <arbre>
    <tronc>
      <branche>
        <feuille/>
      </branche>
    </tronc>
  </arbre>
  <arbre>
    <tronc/>
  </arbre>
  <arbre>
    <tronc>
      <branche>
        <feuille/>
      </branche>
    </tronc>
  </arbre>
</foret>

=== HamkitSi/HamkitSi.github.io/portfolio-hasina-rakotoarison/tp1/bon2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foret SYSTEM "arbres.dtd">
<foret>
  <arbre>
    <tronc>
      <branche>
        <feuille/>
      </branche>
    </tronc>
  </arbre>
  <arbre>
    <tronc>
      <branche>
        <branche>
          <branche>
            <feuille/>
          </branche>
        </branche>
      </branche>
    </tronc>
  </arbre>
</foret>

=== HamkitSi/HamkitSi.github.io/portfolio-hasina-rakotoarison/tp1/bon4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foret SYSTEM "arbres.dtd">
<foret>
  <arbre>
    <tronc>
      <branche>
        <feuille/>
      </branche>
    </tronc>
  </arbre>
  un sentier
  <arbre>
    <tronc>
      <branche>
        <branche>
          <feuille/>
        </branche>
      </branche>
    </tronc>
  </arbre>
</foret>
